---
- name: Install Docker Compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}'
    dest: "/usr/bin/docker-compose"
    mode: 0755
...
