---
- name: Remove Previous Versions
  apt:
    name: docker, docker-engine, docker.io, containerd, runc
    state: absent

- name: Docker Repository Prerequisites
  apt:
    name: apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common
    state: present

- name: Add Docker GPG Key
  shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - warn=no"

- name: Setup Docker Repository
  shell: 'echo | add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"'

- name: Update
  apt:
    update_cache: yes
  ignore_errors: true

- name: Install Docker
  apt:
    name: docker-ce, docker-ce-cli, containerd.io
    state: latest
  ignore_errors: true
...
