---
- name: Install BOSH CLI
  get_url:
    url: "https://github.com/cloudfoundry/bosh-cli/releases/download/v{{ bosh_version}}/bosh-cli-{{ bosh_version }}-linux-amd64"
    dest: "/home/{{ jumpbox_user }}/bin/bosh"
    owner: "{{ jumpbox_user }}"
    group: "{{ jumpbox_group }}"
    mode: 0755
...
