---
- name: Check Installed credhub Version
  shell: "/home/{{ jumpbox_user }}/bin/credhub --version"
  changed_when: false
  failed_when: false
  register: credhub_state

- name: Install credhub
  block:
    - name: Download credhub
      get_url:
        url: "https://github.com/cloudfoundry-incubator/credhub-cli/releases/download/{{ credhub_version }}/credhub-linux-{{ credhub_version }}.tgz"
        dest: "/home/{{ jumpbox_user }}/bin/credhub.tgz"
        owner: "{{ jumpbox_user }}"
        group: "{{ jumpbox_group }}"
        mode: 0644

    - name: Untar credhub
      unarchive:
        src: "/home/{{ jumpbox_user }}/bin/credhub.tgz"
        dest: "/home/{{ jumpbox_user }}/bin/"
        owner: "{{ jumpbox_user }}"
        group: "{{ jumpbox_group }}"
        mode: 0755
        remote_src: yes

    - name: Remove Tar File
      file:
        dest: "/home/{{ jumpbox_user }}/bin/credhub.tgz"
        state: absent
  when: credhub_state.stdout.find(credhub_version | string) == -1
...
