---
- name: Install om
  get_url:
    url: "https://github.com/pivotal-cf/om/releases/download/{{ om_version}}/om-linux-{{ om_version}}"
    dest: "/home/{{ jumpbox_user }}/bin/om"
    owner: "{{ jumpbox_user }}"
    group: "{{ jumpbox_group }}"
    mode: 0755
...
